# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-02 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_linuxinfo_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='commit',
            field=models.CharField(help_text='record commit', max_length=200, verbose_name='record commit'),
        ),
    ]
