# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-07 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20200302_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectdInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_idle', models.TextField(help_text='cpu_idle', verbose_name='cpu_idle')),
                ('cpu_interrupt', models.TextField(help_text='cpu_interrupt', verbose_name='cpu_interrupt')),
                ('cpu_nice', models.TextField(help_text='cpu_nice', verbose_name='cpu_nice')),
                ('cpu_softirq', models.TextField(help_text='cpu_softirq', verbose_name='cpu_softirq')),
                ('cpu_steal', models.TextField(help_text='cpu_steal', verbose_name='cpu_steal')),
                ('cpu_system', models.TextField(help_text='cpu_system', verbose_name='cpu_system')),
                ('cpu_user', models.TextField(help_text='cpu_user', verbose_name='cpu_user')),
                ('cpu_wait', models.TextField(help_text='cpu_wait', verbose_name='cpu_wait')),
            ],
            options={
                'verbose_name': 'collectd info',
                'verbose_name_plural': 'collectd info',
            },
        ),
    ]
