# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-08 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_collectdinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='collectd_info',
            field=models.ForeignKey(default=1, help_text='collectd info', on_delete=django.db.models.deletion.CASCADE, to='records.CollectdInfo', verbose_name='collectd info'),
            preserve_default=False,
        ),
    ]
