# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-08 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20200308_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='collectd_info',
            field=models.ForeignKey(default='100', help_text='collectd info', on_delete=django.db.models.deletion.CASCADE, to='records.CollectdInfo', verbose_name='collectd info'),
        ),
    ]
