# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-03 17:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='alias name')),
                ('is_used', models.BooleanField(default=False, verbose_name='is_used')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('alias', models.CharField(blank=True, default='', max_length=100)),
                ('machine_secret', models.CharField(blank=True, default='', max_length=32, verbose_name='machine secret')),
                ('sn', models.CharField(blank=True, default='', max_length=16)),
                ('os_name', models.CharField(blank=True, default='', max_length=100)),
                ('os_version', models.CharField(blank=True, default='', max_length=100)),
                ('comp_name', models.CharField(blank=True, default='', max_length=100)),
                ('comp_version', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=10)),
                ('owner_email', models.EmailField(max_length=256, verbose_name='email')),
                ('owner_username', models.CharField(blank=True, default='', max_length=100)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('add_time',),
            },
        ),
    ]
